# auths should definitely be stored in db instead lol
AUTHS = {
    # fill me in with worker auths
}

DB_USER = ...
DB_PASS = ...
DB_HOST = "localhost"
DB_PORT = 3306
DB_DATABASE = ...

B2_APP_KEY_ID = ...
B2_APP_KEY = ...
B2_BUCKET = ...

TMP_DIR = ...

BOARDS_BASE = "https://board.portal2.sr"

RANK_THRESHOLD = 10

WEBHOOK_URL = ...
